language: php

dist: trusty
sudo: false

php:
  - nightly
  - 7.4
  - 8.0
  - 8.1

env:
  - COMPOSER_MEMORY_LIMIT=-1

matrix:
  allow_failures:
    - php: nightly

install:
  - PHP_VER=$(php -r "echo PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION . '.' . PHP_RELEASE_VERSION;")
  - travis_retry composer update

before_script:
  - composer show

script:
  - ./dev-tools/vendor/bin/php-cs-fixer --diff --dry-run -v --allow-risky=yes fix && ./dev-tools/vendor/bin/php-cs-fixer --diff --dry-run -v --allow-risky=yes fix .php_cs.dist
  - vendor/bin/phpunit

after_script:
  - travis_retry bin/coveralls.sh
